### ISSUE TITLE
For libraries and fonts

### ISSUE THREAD

**Issue by saturngod** [khzaw/awesome-myanmar-unicode#2]
I wrote Zawgyi <=> Unicode library that support following languages.
- Java
- Objective-C
- Swift
- Python
- PHP
- Ruby

https://github.com/saturngod/Rabbit

For the font list , please check Khmer Type

https://github.com/search?p=1&q=user%3Akhmertype+Myanmar&type=Repositories

He did 15 fonts design for Myanmar Unicode

**Comment by nainglinaung** [comment]
hopefully, that list will ring too 

https://dl.dropboxusercontent.com/u/283860/host/bookmarklet/index.html

**Comment by khzaw** [comment]
@saturngod @nainglinaung Thanks for the suggestions. I'm update the list later. Currently in class.

**Comment by khzaw** [comment]
@saturngod Updated, thanks!
